//
//  SwiftModelGenerator.swift
//  LF-Paper
//

import Foundation

/// Writes Swift source for a model schema: a header on how to use it, then each type,
/// then `JSONValue` or helper functions when they're needed.
nonisolated enum SwiftModelGenerator {
    static func source(for schema: SwiftModelSchema, options: SwiftModelOptions, jsonFileName: String) -> String {
        let declarations = options.kind.usesCodable
            ? CodableModelWriter(schema: schema, options: options).declarations()
            : DictionaryModelWriter(schema: schema, options: options).declarations()
        let header = header(for: schema, options: options, jsonFileName: jsonFileName)
        return ([header, "import Foundation"] + declarations).joined(separator: "\n\n") + "\n"
    }

    /// A Swift string literal for `text`.
    static func stringLiteral(_ text: String) -> String {
        var escaped = ""
        for scalar in text.unicodeScalars {
            switch scalar {
            case "\\": escaped += "\\\\"
            case "\"": escaped += "\\\""
            case "\n": escaped += "\\n"
            case "\r": escaped += "\\r"
            case "\t": escaped += "\\t"
            case _ where scalar.value < 0x20: escaped += "\\u{\(String(scalar.value, radix: 16))}"
            default: escaped.unicodeScalars.append(scalar)
            }
        }
        return "\"\(escaped)\""
    }

    /// `access` followed by a space, or nothing for internal.
    static func accessPrefix(_ options: SwiftModelOptions) -> String {
        options.isPublic ? "public " : ""
    }

    /// Parameters on one line when there are few, one per line otherwise.
    static func parameterList(_ parameters: [String], indent: String) -> String {
        guard parameters.count > 3 else { return "(\(parameters.joined(separator: ", ")))" }
        let lines = parameters.map { "\(indent)    \($0)" }.joined(separator: ",\n")
        return "(\n\(lines)\n\(indent))"
    }

    private static func header(for schema: SwiftModelSchema, options: SwiftModelOptions, jsonFileName: String) -> String {
        let root = schema.rootName
        let rootType = schema.isRootArray ? "[\(root)]" : root
        var lines = ["//", "//  \(root).swift", "//  Generated by LF-Paper from \(jsonFileName).", "//"]
        switch options.kind {
        case .codable, .decodable, .classes:
            lines.append("//  Decode with:")
            lines.append("//      let \(schema.isRootArray ? "models" : "model") = try JSONDecoder().decode(\(rootType).self, from: data)")
        case .encodable:
            lines.append("//  Encode with:")
            lines.append("//      let data = try JSONEncoder().encode(\(schema.isRootArray ? "models" : "model"))")
        case .dictionary:
            lines.append("//  Read with:")
            if schema.isRootArray {
                lines.append("//      let objects = try JSONSerialization.jsonObject(with: data) as? [[String: Any]] ?? []")
                lines.append("//      let models = objects.compactMap(\(root).init(dictionary:))")
            } else {
                lines.append("//      let object = try JSONSerialization.jsonObject(with: data) as? [String: Any] ?? [:]")
                lines.append("//      let model = \(root)(dictionary: object)")
            }
        }
        if schema.usesDates, options.kind.usesCodable {
            let strategy = options.kind == .encodable ? "encoder.dateEncodingStrategy" : "decoder.dateDecodingStrategy"
            lines.append("//  Dates are ISO 8601, so first set \(strategy) = .iso8601")
        }
        return lines.joined(separator: "\n")
    }
}

/// Codable, Decodable or Encodable structs, or Codable final classes.
nonisolated struct CodableModelWriter {
    let schema: SwiftModelSchema
    let options: SwiftModelOptions

    private var access: String { SwiftModelGenerator.accessPrefix(options) }
    private var isClass: Bool { options.kind == .classes }

    func declarations() -> [String] {
        schema.declarations.map(declaration) + (schema.usesJSONValue ? [jsonValueDeclaration()] : [])
    }

    private var baseConformance: String {
        switch options.kind {
        case .decodable: "Decodable"
        case .encodable: "Encodable"
        case .codable, .classes, .dictionary: "Codable"
        }
    }

    private func conformances(of declaration: SwiftDeclaration) -> [String] {
        let extras = options.effectiveConformances.filter { $0 != .identifiable || hasHashableID(declaration) }
        return [baseConformance] + extras.map(\.rawValue)
    }

    /// `Identifiable` needs an `id` whose type is `Hashable`.
    private func hasHashableID(_ declaration: SwiftDeclaration) -> Bool {
        guard let id = declaration.properties.first(where: { $0.name == "id" }) else { return false }
        return isHashable(id.type)
    }

    /// Generated types are `Hashable` only when that was chosen; `JSONValue` always is.
    private func isHashable(_ type: SwiftType) -> Bool {
        switch type {
        case .bool, .int, .double, .string, .date, .url, .jsonValue: true
        case .named: options.effectiveConformances.contains(.hashable)
        case .array(let item), .optional(let item): isHashable(item)
        }
    }

    private func declaration(_ declaration: SwiftDeclaration) -> String {
        let keyword = isClass ? "final class" : "struct"
        let binding = options.usesVar ? "var" : "let"
        var sections: [String] = []
        sections.append(declaration.properties.map { property in
            let comment = property.isUnknownItemType ? " // empty in the sample, so the item type is unknown" : ""
            return "    \(access)\(binding) \(SwiftNaming.escaped(property.name)): \(spelling(of: property.type))\(comment)"
        }.joined(separator: "\n"))
        if declaration.needsCodingKeys {
            sections.append(codingKeys(for: declaration))
        }
        if isClass || options.isPublic {
            sections.append(initializer(for: declaration))
        }
        if isClass {
            sections += equality(for: declaration)
        }
        let body = sections.filter { !$0.isEmpty }.joined(separator: "\n\n")
        let conformances = conformances(of: declaration).joined(separator: ", ")
        return "\(access)\(keyword) \(declaration.name): \(conformances) {\n\(body)\n}"
    }

    private func codingKeys(for declaration: SwiftDeclaration) -> String {
        let cases = declaration.properties.map { property in
            let name = SwiftNaming.escaped(property.name)
            return property.name == property.jsonKey
                ? "        case \(name)"
                : "        case \(name) = \(SwiftModelGenerator.stringLiteral(property.jsonKey))"
        }
        return (["    enum CodingKeys: String, CodingKey {"] + cases + ["    }"]).joined(separator: "\n")
    }

    private func initializer(for declaration: SwiftDeclaration) -> String {
        let parameters = declaration.properties.map { property in
            "\(SwiftNaming.escaped(property.name)): \(spelling(of: property.type))\(property.isOptional ? " = nil" : "")"
        }
        let assignments = declaration.properties.map { property in
            let name = SwiftNaming.escaped(property.name)
            return "        self.\(name) = \(name)"
        }
        let signature = "    \(access)init\(SwiftModelGenerator.parameterList(parameters, indent: "    "))"
        return ([signature + " {"] + assignments + ["    }"]).joined(separator: "\n")
    }

    /// Classes don't get `==` and `hash(into:)` synthesized; compare and hash every property.
    private func equality(for declaration: SwiftDeclaration) -> [String] {
        let conformances = options.effectiveConformances
        guard conformances.contains(.hashable) || conformances.contains(.equatable) else { return [] }
        let names = declaration.properties.map { SwiftNaming.escaped($0.name) }
        let comparison = names.isEmpty
            ? "true"
            : names.map { "lhs.\($0) == rhs.\($0)" }.joined(separator: "\n            && ")
        var functions = [
            """
                \(access)static func == (lhs: \(declaration.name), rhs: \(declaration.name)) -> Bool {
                    \(comparison)
                }
            """,
        ]
        if conformances.contains(.hashable) {
            let combines = names.map { "        hasher.combine(\($0))" }
            functions.append((["    \(access)func hash(into hasher: inout Hasher) {"] + combines + ["    }"]).joined(separator: "\n"))
        }
        return functions
    }

    private func spelling(of type: SwiftType) -> String {
        switch type {
        case .bool: "Bool"
        case .int: "Int"
        case .double: "Double"
        case .string: "String"
        case .date: "Date"
        case .url: "URL"
        case .named(let name): name
        case .array(let item): "[\(spelling(of: item))]"
        case .optional(let wrapped): "\(spelling(of: wrapped))?"
        case .jsonValue: "JSONValue"
        }
    }

    private func jsonValueDeclaration() -> String {
        var sections = [
            """
            /// A value whose type differs across the sample, or couldn't be told from it.
            \(access)enum JSONValue: \(baseConformance), Hashable, Sendable {
                case string(String)
                case number(Double)
                case bool(Bool)
                case object([String: JSONValue])
                case array([JSONValue])
                case null
            """,
        ]
        if options.kind != .encodable {
            sections.append("""
                \(access)init(from decoder: any Decoder) throws {
                    let container = try decoder.singleValueContainer()
                    if container.decodeNil() {
                        self = .null
                    } else if let value = try? container.decode(Bool.self) {
                        self = .bool(value)
                    } else if let value = try? container.decode(Double.self) {
                        self = .number(value)
                    } else if let value = try? container.decode(String.self) {
                        self = .string(value)
                    } else if let value = try? container.decode([JSONValue].self) {
                        self = .array(value)
                    } else {
                        self = .object(try container.decode([String: JSONValue].self))
                    }
                }
            """)
        }
        if options.kind != .decodable {
            sections.append("""
                \(access)func encode(to encoder: any Encoder) throws {
                    var container = encoder.singleValueContainer()
                    switch self {
                    case .string(let value): try container.encode(value)
                    case .number(let value): try container.encode(value)
                    case .bool(let value): try container.encode(value)
                    case .object(let value): try container.encode(value)
                    case .array(let value): try container.encode(value)
                    case .null: try container.encodeNil()
                    }
                }
            """)
        }
        return sections.joined(separator: "\n\n") + "\n}"
    }
}
